# Generated by Django 5.2.4 on 2025-12-07 08:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_course', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Actif'), (2, 'Archivé')], default=0)),
                ('estimated_duration', models.IntegerField(default=0, help_text='Total course duration in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_required_time', models.IntegerField(default=0, help_text='Minimum time required to complete in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cours.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Actif'), (2, 'Archivé')], default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimated_duration', models.IntegerField(default=0, help_text='Module total duration in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_required_time', models.IntegerField(default=0, help_text='Minimum time required for module in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cours.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Actif'), (2, 'Archivé')], default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimated_duration', models.IntegerField(default=0, help_text='Content duration in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_required_time', models.IntegerField(default=0, help_text='Minimum time required for content in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('completed_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de complétions')),
                ('average_rating', models.FloatField(default=0, verbose_name='Note moyenne')),
                ('completion_rate', models.FloatField(default=0, verbose_name='Taux de complétion')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.contenttype')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='cours.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PDFContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('page_count', models.IntegerField(default=0, help_text='Number of pages in PDF', validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_reading_time', models.IntegerField(default=0, help_text='Estimated reading time in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('course_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_content', to='cours.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='QCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('passing_score', models.IntegerField(default=80)),
                ('max_attempts', models.IntegerField(default=3)),
                ('time_limit', models.IntegerField(default=0)),
                ('course_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qcm', to='cours.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='QCMCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.FloatField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('attempts_count', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.qcm')),
            ],
        ),
        migrations.CreateModel(
            name='QCMQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='single', max_length=10)),
                ('points', models.IntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cours.qcm')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QCMOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cours.qcmquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_score', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total time spent on course in seconds')),
                ('average_time_per_session', models.IntegerField(default=0, help_text='Average session time in seconds')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_contents', models.ManyToManyField(blank=True, related_name='completed_by_users', to='cours.coursecontent')),
                ('completed_qcms', models.ManyToManyField(blank=True, through='cours.QCMCompletion', to='cours.qcm')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subscriptions', to='cours.course')),
                ('locked_contents', models.ManyToManyField(blank=True, related_name='locked_for_users', to='cours.coursecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddField(
            model_name='qcmcompletion',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.subscription'),
        ),
        migrations.AddField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_courses', through='cours.Subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/%y')),
                ('duration', models.IntegerField(default=0, help_text='Video duration in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('course_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='cours.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.coursecontent')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='cours.enrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'content')},
            },
        ),
        migrations.CreateModel(
            name='QCMAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(default=0)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cours.qcm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_attempts', to=settings.AUTH_USER_MODEL)),
                ('selected_options', models.ManyToManyField(to='cours.qcmoption')),
            ],
            options={
                'unique_together': {('user', 'qcm', 'attempt_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='qcmcompletion',
            unique_together={('subscription', 'qcm')},
        ),
    ]
