# Generated by Django 5.2.4 on 2025-12-15 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3498db', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='DetailedTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Durée en secondes')),
                ('progress_before', models.FloatField(default=0, help_text='Progression avant la session')),
                ('progress_after', models.FloatField(default=0, help_text='Progression après la session')),
                ('session_type', models.CharField(choices=[('view', 'Visualisation'), ('read', 'Lecture'), ('practice', 'Pratique'), ('review', 'Révision')], default='view', max_length=50)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_time_tracking', to='cours.coursecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_time_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detailed_time_tracking',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Durée en secondes')),
                ('session_type', models.CharField(choices=[('content', 'Contenu'), ('quiz', 'Quiz'), ('reading', 'Lecture'), ('video', 'Vidéo'), ('practice', 'Pratique')], default='content', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.coursecontent')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking', to='cours.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_tracking',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cours.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('course_activated', 'Course Activated'), ('module_activated', 'Module Activated'), ('content_activated', 'Content Activated'), ('qcm_result', 'QCM Result'), ('system', 'System Announcement'), ('message', 'New Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.coursecontent')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.course')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='cours_notif_user_id_9a72b0_idx'), models.Index(fields=['created_at'], name='cours_notif_created_9bfdcd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cours.course')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.tag')),
            ],
            options={
                'unique_together': {('course', 'tag')},
            },
        ),
    ]
