# Generated by Django 5.2.4 on 2025-12-15 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_tag_detailedtimetracking_timetracking_favoritecourse_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('archived', 'Archivé')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu'), ('pending', 'En attente')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_formations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_groups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'Membre'), ('moderator', 'Modérateur'), ('admin', 'Administrateur')], default='member', max_length=50),
        ),
        migrations.CreateModel(
            name='OrganizationDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_members', models.IntegerField(default=0)),
                ('inactive_members', models.IntegerField(default=0)),
                ('total_learning_time', models.IntegerField(default=0)),
                ('courses_started', models.IntegerField(default=0)),
                ('courses_completed', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='users.organization')),
            ],
            options={
                'db_table': 'organization_daily_stats',
                'ordering': ['-date'],
                'unique_together': {('organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserThemeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_spent', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('completed_contents', models.IntegerField(default=0)),
                ('total_contents', models.IntegerField(default=0)),
                ('strength_level', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('fort', 'Fort')], default='faible', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_theme_stats',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
